/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var View=laya.ui.View;
var Dialog=laya.ui.Dialog;
var Scene=Laya.Scene;
var REG = Laya.ClassUtils.regClass;