/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameDirector from "./script/GameDirector"
import Weapon from "./script/Weapon"
import GameUI from "./view/GameUI"
import Bullet from "./script/Bullet"
import Soldier from "./script/Soldier"
import Enemy from "./script/Enemy"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameDirector.js",GameDirector);
		reg("script/Weapon.js",Weapon);
		reg("view/GameUI.js",GameUI);
		reg("script/Bullet.js",Bullet);
		reg("script/Soldier.js",Soldier);
		reg("script/Enemy.js",Enemy);
    }
}
GameConfig.width = 640;
GameConfig.height = 1336;
GameConfig.scaleMode ="exactfit";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Game.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
