/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Guide from "./script/Guide"
import GameUI from "./view/GameUI"
import GameDirector from "./script/GameDirector"
import Enemy from "./script/Enemy"
import Soldier from "./script/Soldier"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/Guide.js",Guide);
		reg("view/GameUI.js",GameUI);
		reg("script/GameDirector.js",GameDirector);
		reg("script/Enemy.js",Enemy);
		reg("script/Soldier.js",Soldier);
    }
}
GameConfig.width = 640;
GameConfig.height = 1336;
GameConfig.scaleMode ="exactfit";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "GameMain.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
